name: Python

on:
  workflow_dispatch:
  schedule:
    - cron: "15 */01 * * *"
  push:
    branches: ["main"]

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip --quiet
          if [ -f requirements.txt ]; then pip install -r requirements.txt --quiet; fi
          python -m camoufox fetch
        
      - name: Importar arquivo .env
        env:
          PATH_ENV: ${{ secrets.PATH_ENV }}
        run: echo "$PATH_ENV" > .env

      - name: Executar script Python
        env:
          URL: ${{ secrets.URL }}
          API_KEY: ${{ secrets.API_KEY }}
          LOGIN: ${{ secrets.LOGIN }}
          REF: ${{ secrets.REF }}
          USER_AGENT: ${{ secrets.USER_AGENT }}
          COMANDO: ${{ secrets.COMANDO }}
        timeout-minutes: 30
        continue-on-error: true
        run: python app.py

      - name: Upload da captura
        uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: screenshot
          path: screen.png
